<!DOCTYPE html PUBLIC "-//W3C//DTD html 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
	<title>Barehuesos - <?php echo $this->title;?></title>
	<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/javascript/jquery-1.3.2.min.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/javascript/test.js"></script>
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl; ?>/public/style/style.css" media="screen" />
</head>
<body> 
<div id="master" class="section"> 
